In [3]:
import numpy as np

# Nomor 1

In [87]:
a = np.arange(1,28)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27])

In [42]:
a.reshape(3,9)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24, 25, 26, 27]])

In [43]:
a.reshape(3,3,3)

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24],
        [25, 26, 27]]])

# Nomor 2

In [159]:
x = np.random.randint(50, size=(16))
x

array([20,  9, 45, 42, 21, 20,  5, 17,  9, 11, 46, 28,  9, 43, 37,  1])

In [160]:
x.reshape(4,4)

array([[20,  9, 45, 42],
       [21, 20,  5, 17],
       [ 9, 11, 46, 28],
       [ 9, 43, 37,  1]])

In [167]:
x = x.reshape(4,4)
a = np.ones((4,4),int)

a[0]=x[3]
a[1]=x[2]
a[2]=x[1]
a[3]=x[0]

a

array([[ 9, 43, 37,  1],
       [ 9, 11, 46, 28],
       [21, 20,  5, 17],
       [20,  9, 45, 42]])

# Nomor 3

In [176]:
x = np.zeros((10,10))
x 

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [181]:
x[[0]] = np.ones(10)*4
x[[9]] = np.ones(10)*4
x = x.T
x[[0]] = np.ones(10)*4
x[[9]] = np.ones(10)*4
x

array([[4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [4., 0., 0., 0., 0., 0., 0., 0., 0., 4.],
       [4., 0., 0., 0., 0., 0., 0., 0., 0., 4.],
       [4., 0., 0., 0., 0., 0., 0., 0., 0., 4.],
       [4., 0., 0., 0., 0., 0., 0., 0., 0., 4.],
       [4., 0., 0., 0., 0., 0., 0., 0., 0., 4.],
       [4., 0., 0., 0., 0., 0., 0., 0., 0., 4.],
       [4., 0., 0., 0., 0., 0., 0., 0., 0., 4.],
       [4., 0., 0., 0., 0., 0., 0., 0., 0., 4.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.]])

# Nomor 4

In [34]:
import pandas as pd

In [42]:
angka = np.arange(1,26)
abjad = pd.Series(np.arange(1,27), index=["a","b","c","d","e","f","g","h","i","j","k","l","m","n","o","p","q","r","s","t","u","v","w","x","y","z"])

abjad

a     1
b     2
c     3
d     4
e     5
f     6
g     7
h     8
i     9
j    10
k    11
l    12
m    13
n    14
o    15
p    16
q    17
r    18
s    19
t    20
u    21
v    22
w    23
x    24
y    25
z    26
dtype: int32

## Nomor 5

In [227]:
x = np.random.randint(1,6,100)
x

array([3, 2, 3, 2, 3, 1, 3, 4, 4, 2, 3, 2, 4, 3, 4, 4, 1, 1, 4, 3, 2, 1,
       2, 3, 4, 1, 5, 2, 3, 3, 4, 4, 1, 4, 3, 1, 5, 4, 3, 4, 3, 3, 1, 5,
       5, 3, 3, 2, 5, 3, 5, 3, 3, 1, 2, 2, 1, 2, 1, 4, 3, 2, 1, 3, 4, 5,
       1, 5, 5, 3, 5, 2, 3, 5, 3, 2, 1, 1, 4, 1, 1, 1, 5, 4, 1, 2, 5, 3,
       1, 3, 3, 2, 5, 3, 3, 2, 2, 1, 3, 1])

In [228]:
df = pd.DataFrame(x)
df

0
0   3
1   2
2   3
3   2
4   3
.. ..
95  2
96  2
97  1
98  3
99  1

[100 rows x 1 columns]

In [253]:
df1 = df.value_counts()
print(df1)

3    30
1    22
2    18
4    16
5    14
dtype: int64


In [246]:
from scipy import stats
print(stats.mode(x))

ModeResult(mode=array([3]), count=array([30]))


AttributeError: 'Series' object has no attribute 'DataFrame'