In [3]:
x=0
y=5

if x < y:
    print('yes')
if y < x:
    print ('yes')
if x:
    print ('yes')
if y:
    print ('yes')
if 'aul' in 'grault':
    print ('yes')
if 'quux' in ['foo','bar','baz']:
    print ('yes')
    

yes
yes
yes


In [4]:
if 'id' in 'Sidik':
    print ('sesuai')

sesuai


In [5]:
#Eliminasi Gauss menghasilkan matriks segitiga kiri bawah
import numpy as np

#Input pada matriks asal
A = np.array([[1, 2, 2, 3, 4],
              [4, 9, 10, 13, 17],
              [2, 6, 7, 10, 14],
              [3, 10, 20, 22, 40],
              [1, 5, 10, 12, 16]])
B = np.array([2, 2, 2, 2, 2])
n = len(B)

print('Bentuk Matriks asal')
print(A, B)

#Menggunakan Eliminasi
for k in range(0, n-1):
    for i in range(k+1, n):
        rasio = A[i,k]/A[k,k]
        for j in range(k, n):
            A[i,j] -= rasio*A[k,j]
        B[i] -= rasio*B[k]
        
x = np.zeros(n)

x[n-1] = B[n-1]/A[n-1, n-1]
for i in range(n-2, -1, -1):
    sum_j = 0
    for j in range(i+1, n):
        sum_j += A[i,j]*x[j]
    x[i] = (B[i] - sum_j)/A[i,i]

print('')
print('Matriks hasil eliminasi')
print(A, B, x)

#Pivoting hasil
print('')
print('Hasil eliminasi setelah pivoting')
result = [[A[j,i] for j in range(len(A))] for i in range(len(A[0]))]
for r in result:
   print(r)

Bentuk Matriks asal
[[ 1  2  2  3  4]
 [ 4  9 10 13 17]
 [ 2  6  7 10 14]
 [ 3 10 20 22 40]
 [ 1  5 10 12 16]] [2 2 2 2 2]

Matriks hasil eliminasi
[[ 1  2  2  3  4]
 [ 0  1  2  1  1]
 [ 0  0 -1  2  4]
 [ 0  0  0 21 48]
 [ 0  0  0  0 -5]] [ 2 -6 10 80  0] [ 5.42857143 -5.04761905 -2.38095238  3.80952381 -0.        ]

Hasil eliminasi setelah pivoting
[1, 0, 0, 0, 0]
[2, 1, 0, 0, 0]
[2, 2, -1, 0, 0]
[3, 1, 2, 21, 0]
[4, 1, 4, 48, -5]
