In [1]:
import numpy as np

In [4]:
a = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12]
])

print(a[1,2])

7


In [5]:
np.empty(3)

array([ 0.00000000e+000,  1.30028947e-311, -0.00000000e+000])

In [6]:
np.ones(4)

array([1., 1., 1., 1.])

In [7]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [10]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [15]:
np.ones((1,3))

array([[1., 1., 1.]])

In [16]:
np.zeros((3,1))

array([[0.],
       [0.],
       [0.]])

In [17]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [18]:
np.linspace(0,10,50)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

In [19]:
np.random.rand(2)

array([0.64154937, 0.28794569])

In [25]:
np.random.rand(3,3)

array([[0.68423548, 0.89060171, 0.0355979 ],
       [0.7323409 , 0.8841481 , 0.97570703],
       [0.05313424, 0.5356904 , 0.37996081]])

In [33]:
np.random.randint(0,10)

2

In [38]:
np.random.randint(0,10,3)

array([4, 0, 7])

In [63]:
arr= np.array([1,2,3,4,5,6,8,9,10])
arr

array([ 1,  2,  3,  4,  5,  6,  8,  9, 10])

In [66]:
arr.dtype

dtype('int32')

In [67]:
np.append(arr,[11,12])

array([ 1,  2,  3,  4,  5,  6,  8,  9, 10, 11, 12])

In [78]:
np.delete(arr,1)

array([ 1,  3,  4,  5,  6,  8,  9, 10])

In [79]:
arr= np.array([3,5,6,3,2,7,1])
arr

array([3, 5, 6, 3, 2, 7, 1])

In [83]:
np.sort(arr)

array([1, 2, 3, 3, 5, 6, 7])

In [87]:
array_example= np.array([
    [1,2,3,4,5],
    [2,3,4,4,5],
    [4,5,6,7,8],
    [2,3,4,5,6],
    [7,5,4,4,2],
])
array_example

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 4, 5],
       [4, 5, 6, 7, 8],
       [2, 3, 4, 5, 6],
       [7, 5, 4, 4, 2]])

In [88]:
array_example[2,3]

7

In [89]:
array_example.ndim

2

In [91]:
array_example.size

25

In [92]:
array_example.shape

(5, 5)

In [93]:
example= np.array([
    [[1,2,3,4,5],
    [2,3,4,4,5]],
    [[4,5,6,7,8],
    [2,3,4,5,6]],
    [[7,5,4,4,2],
     [3,4,5,6,7]]
])
example

array([[[1, 2, 3, 4, 5],
        [2, 3, 4, 4, 5]],

       [[4, 5, 6, 7, 8],
        [2, 3, 4, 5, 6]],

       [[7, 5, 4, 4, 2],
        [3, 4, 5, 6, 7]]])

In [116]:
#astype(int) Pembulatan hasil random yg float
a= np.random.random((5,2))
a= a.astype(int)
a

array([[0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0]])